services:
  database:
    image: postgres:18.1
    restart: always
    container_name: teslodb
    ports:
      - '5032:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql

  #tesloapp:
  #  build: ./
  #  restart: always
  #  container_name: tesloShopApi
  #  ports:
  #    - '3010:${PORT}'
  #  volumes:
  #    - ./:/app
