services:
  production_line_db:
    image: postgres:17.4
    restart: always
    container_name: production_line_db
    ports:
      - '${DB_PORT_EXPOSE}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  production_line_backend:
    image: production_line:backend
    container_name: production_line_api
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./.env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - production_line_db
    restart: always
